baseURL = "https://planning-assistance.co.uk"
relativeURLs = true
canonifyURLs = true

languageCode = "en-GB"
paginate = 6
title = "Planning Assistance"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Services"
url = "#service"
weight = 2
[[menu.main]]
name = "About"
url = "#about"
weight = 3
[[menu.main]]
name = "Expertise"
url = "#resume"
weight = 4
[[menu.main]]
name = "Detail"
url = "#detail"
weight = 5
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Asked Questions"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3

[params]
blogPageURL = "detail"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/mvollppz"
googleAnalytics = "G-CJK8C1K8Y0"
logo = "images/site-navigation/logo.png"

[params.address]
email = "youngercora@gmail.com"
openingHours = "Open from 9am to 5pm (closed weekends)"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/Planning-Assistance-111675564881572"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/planning-assistance-uk"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/planningassist1"
weight = 3
